name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Run OWASP Dependency-Check
        run: |
          mkdir -p report
          curl -sSLo dc.zip https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
          unzip -q dc.zip
          chmod +x dependency-check/bin/dependency-check.sh
          # Run scan with NVD API key if available
          if [ -n "${{ secrets.NVD_API_KEY }}" ]; then
            ./dependency-check/bin/dependency-check.sh \
              --project "JavaSecurityCheck" \
              --scan . \
              --format HTML \
              --out report \
              --disableAssembly \
              --nvdApiKey "${{ secrets.NVD_API_KEY }}"
          else
            echo "⚠️ No NVD_API_KEY secret configured — scan may fail or have incomplete data."
            ./dependency-check/bin/dependency-check.sh \
              --project "JavaSecurityCheck" \
              --scan . \
              --format HTML \
              --out report \
              --disableAssembly
          fi
          ls -la report

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: report/**
          if-no-files-found: error
